### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by kw-corne** [ADA-research/auto-verify#25]
# CLI

There *must* be a CLI interface for installing different verifiers onto a linux system.

## Registering cli
In `pyproject.toml`, something like:

```toml
[project.scripts]
auto-verify = "my_package.my_module:main_cli"
```

## Options:
* `install [verifier(s)]`
* `version`
* `help`
*
